try {
	throw new Error('Yeah... Sorry');
}
catch (e) {
	console.log(e);
}
